services:
  # extension backend (python fastAPI)
  extension_backend:
    build: 
      context: ./extension_backend
      dockerfile: Dockerfile
    ports:
      - "${API_PORT_BE}:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - API_DEBUG=${API_DEBUG_BE}
      - API_HOST=${API_HOST_BE}
      - API_PORT=${API_PORT_BE}
      - API_KEY=${API_KEY_BE}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  # web client (react)
  web_client:
    build:
      context: ./web/client
      dockerfile: Dockerfile
    ports:
      - "${WEB_CLIENT_PORT}:3000"
    volumes:
      - ./web/client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${WEB_SERVER_PORT}
    depends_on:
      - web_server
  
  # web server (node)
  web_server:
    build:
      context: ./web/server
      dockerfile: Dockerfile
    ports:
      - "${WEB_SERVER_PORT}:5000"
    volumes:
      - ./web/server:/app
      - /app/node_modules
      - ./database:/app/database
    env_file:
      - .env
    environment:
      - PORT=${WEB_SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=http://localhost:${WEB_CLIENT_PORT}
    depends_on:
      - database
    
  # database (postgres)
  database:
    image: postgres:17-alpine
    ports: 
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${DB_AUTH_METHOD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: