name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-all-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # set up node for web components
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # set up python for python components
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      # web client tests
      - name: Install web client dependencies
        working-directory: ./web/client
        run: |
          npm ci
          
      - name: Run web client linting
        working-directory: ./web/client
        run: npm run lint
        
      - name: Build web client
        working-directory: ./web/client
        run: npm run build
      
      # web server tests
      - name: Install web server dependencies
        working-directory: ./web/server
        run: |
          npm ci
          
      - name: Run web server linting
        working-directory: ./web/server
        run: npm run lint
      
      # extension backend tests
      - name: Install extension backend dependencies
        working-directory: ./extension_backend
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint extension backend with flake8
        working-directory: ./extension_backend
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      # chatbot tests
      - name: Install chatbot dependencies
        working-directory: ./chatbot
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint chatbot with flake8
        working-directory: ./chatbot
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics